// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddToListTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addToList() {
    driver.get("https://www.costco.com/.product.100780581.html?ADBUTLERID=homepage_item_driver_sharkvacuum");
    driver.manage().window().setSize(new Dimension(1440, 799));
    js.executeScript("window.scrollTo(0,12)");
    js.executeScript("window.scrollTo(0,346)");
    vars.put("itemName", driver.findElement(By.cssSelector("h1:nth-child(2)")).getText());
    driver.findElement(By.id("add-to-list-button")).click();
    driver.findElement(By.id("list-select-dropdown")).click();
    {
      WebElement dropdown = driver.findElement(By.id("list-select-dropdown"));
      dropdown.findElement(By.xpath("//option[. = 'List']")).click();
    }
    driver.findElement(By.id("costcoModalBtn2")).click();
    {
      WebElement element = driver.findElement(By.id("costcoModalBtn2"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("costcoModalBtn2")).click();
    assertThat(driver.findElement(By.id("wishlist_product_2429514")).getText(), is("vars.get(\"itemName\").toString()"));
  }
}
