// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testInvalidSearch() {
    // Test name: TestInvalidSearch
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.costco.com/");
    // 2 | setWindowSize | 1735x750 | 
    driver.manage().window().setSize(new Dimension(1735, 750));
    // 3 | click | id=search-field | 
    driver.findElement(By.id("search-field")).click();
    // 4 | type | id=search-field | sdfsdfsd
    driver.findElement(By.id("search-field")).sendKeys("sdfsdfsd");
    // 5 | click | css=.btn:nth-child(4) > .co-search-thin | 
    driver.findElement(By.cssSelector(".btn:nth-child(4) > .co-search-thin")).click();
    // 6 | assertText | css=h1:nth-child(1) | We were not able to find a match. Try another search or shop related products.
    assertThat(driver.findElement(By.cssSelector("h1:nth-child(1)")).getText(), is("We were not able to find a match. Try another search or shop related products."));
  }
  @Test
  public void testValidSearch() {
    // Test name: TestValidSearch
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.costco.com/");
    // 2 | click | id=search-field | 
    driver.findElement(By.id("search-field")).click();
    // 3 | type | id=search-field | fridge
    driver.findElement(By.id("search-field")).sendKeys("fridge");
    // 4 | click | css=.btn:nth-child(4) > .co-search-thin | 
    driver.findElement(By.cssSelector(".btn:nth-child(4) > .co-search-thin")).click();
    // 5 | verifyText | css=.t1-style | Refrigerators
    assertThat(driver.findElement(By.cssSelector(".t1-style")).getText(), is("Refrigerators"));
  }
}
