// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestRemoveFromCartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testRemoveFromCart() {
    // Test name: testRemoveFromCart
    // Step # | name | target | value
    // 1 | open | https://www.costco.com/CheckoutCartDisplayView?catalogId=10701&storeId=10301&langId=-1&krypto=vkvAzmEwtOxURB5OKnd1nRI9LJhj%2BCdFTMpqs3F1VT42RLRI5M%2B46ppW0UoIb7quoOFOIlnUncI644%2BnzdSAx8QmsTxyVC36Ug1hpdZZPkQ%3D&ddkey=http%3ACheckoutCartView | 
    driver.get("https://www.costco.com/CheckoutCartDisplayView?catalogId=10701&storeId=10301&langId=-1&krypto=vkvAzmEwtOxURB5OKnd1nRI9LJhj%2BCdFTMpqs3F1VT42RLRI5M%2B46ppW0UoIb7quoOFOIlnUncI644%2BnzdSAx8QmsTxyVC36Ug1hpdZZPkQ%3D&ddkey=http%3ACheckoutCartView");
    // 2 | setWindowSize | 1936x1048 | 
    driver.manage().window().setSize(new Dimension(1936, 1048));
    // 3 | click | id=remove-serial_1926344178 | 
    // Since Costco randomly generates an ID every time, the ID must be taken after adding the product to the cart in order for this command to pass
    driver.findElement(By.id("remove-serial_1926344178")).click();
  }
}
